services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: palge
    ports:
      - "5433:5432"
    volumes:
      - palge_db_data:/var/lib/postgresql/data

volumes:
  palge_db_data:
